### ISSUE TITLE
Timeline not resizing correctly since V2.0 when resizing the browser.

### ISSUE THREAD

**Issue by leducquan** [cerner/terra-graphs#85] opened 2021-03-22 23:43 UTC
# Bug Report

## Description
Since upgrading to V2 of carbon-graphs, we have encountered a resizing issue with the timeline axis and does to resize correctly.

We had a similar issue before but used this.graphInstance.resizeHandler() which solved the resizing issue when on v1.19.0. However since upgrading to V2, it has broken.

I've attached gifs to demonstrate before and after upgrade.

### Graphs affected

* [ ]  Bar graph
* [ ]  Bubble graph
* [ ]  Gantt chart
* [ ]  Line graph
* [ ]  Paired result
* [ ]  Pie chart
* [ ]  Scatter plot
* [x]  Timeline

## Steps to Reproduce
1. Resize browser

## Link to CodeSandbox
Use [this](https://codesandbox.io/s/keen-thunder-nh5gk?file=/src/data.js) template to reproduce the behavior.

## Additional Context / Screenshots

 **with "@cerner/carbon-graphs": "^1.19.0"** 

![resize issue before](https://user-images.githubusercontent.com/19377430/112071512-d6688b00-8b67-11eb-8fcd-5513f5d65aca.gif)

 **with "@cerner/carbon-graphs": "^2.0.0"** 

![resize issue after](https://user-images.githubusercontent.com/19377430/112071516-da94a880-8b67-11eb-81de-8a416314356d.gif)

## Expected Behavior
We expect the graph to resize appropriately as before.

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by sdadn** [comment] 2021-03-26 15:02
Hello @leducquan . Just to clarify, are you using the latest version of Carbon? (2.16.3 as of right now)

**Comment by leducquan** [comment] 2021-03-26 18:30
Hi @sdadn , yes we use ^2.15.0 so would have picked up latest. 2.16.3

**Comment by sdadn** [comment] 2021-03-29 14:21
I've been unable to replicate the issue so far. Can you create a sandbox that demonstrates this bug?

**Comment by gerard-isdell** [comment] 2021-03-30 18:25
Thanks for the catch up call.

From the testing I've been doing, this seems to be something that started with 2.3.0 (at least it works with 2.2.0)

And it's necessary to have an EventLine graph above another graph

It looks like it's not possible to pull in Stella Timeline and components hosted on cernrepos.net to the sandbox, but we'll try and re-create the issues with the sandbox

**Comment by gerard-isdell** [comment] 2021-03-31 14:01
Hi - I've two questions. 

1) Should we be using @cerner/carbon-graphs or @cerner/terra-graphs?

2) Should it be possible for the width of carbon-axis-x to be out of sync with the width of carbon-graph-canvas.

When we load the component they are in sync
![TimelineAxisWidthSame](https://user-images.githubusercontent.com/16339189/113153533-1b0eb900-922f-11eb-9eba-24f4c54d85c8.png)

But after resizing (to a point where the ticks are recalculated) they become out of sync
![TimelineAxisWidthDiff](https://user-images.githubusercontent.com/16339189/113153633-337ed380-922f-11eb-9b90-10f44a321399.png)


Also I'm seeing an error in the console, when this issue arises

>  null is not an object (evaluating 't.style')
>  at 
>  Bv
> n.canvasWidth = parseInt(t.style("width"), 10) - pg(t)
>  N.e.resize
> this.config.showLegend && (this.legendSVG = Ch(this.config, this.config.bindLegendTo ? De(this.config.bindLegendTo) : e)),
> 

I don't think we can use the sandbox as we can't pull in timeline, But I can create a branch you can build to reproduce the issue, if that would help

**Comment by gerard-isdell** [comment] 2021-04-06 11:39
I don't think the style issue is related to the x-axis problem.

But I have rebuild Stella Timeline with version 2.2.1 and 2.2.2, and it looks like these changes are causing the issue in Stella Timeline
https://github.com/cerner/carbon-graphs/releases/tag/v2.2.2

**Comment by gerard-isdell** [comment] 2021-04-08 15:44
Hi @sdadn   Is there a JIRA to track this issue, or is it all done using the GitHub issue?

**Comment by sdadn** [comment] 2021-04-08 16:07
@gerard-isdell Currently, open source projects are tracked though GitHub.

**Comment by gerard-isdell** [comment] 2021-04-12 13:15
Hi @sdadn Just wondering if you have any update on this?  Thanks

**Comment by sdadn** [comment] 2021-04-12 16:54
Moving the investigation subtask of this issue to #93 as part of our scrum process.

**Comment by gerard-isdell** [comment] 2021-04-13 11:59
Hi @sdadn  Does the "🚧 blocked: engineering input needed" label mean you're waiting for input from my team?

**Comment by mjhenkes** [comment] 2021-04-13 12:55
@gerard-isdell, the "🚧 blocked: engineering input needed" label means that we need to spike on the technical approach before we can start working on the issue.

**Comment by gerard-isdell** [comment] 2021-04-13 13:57
Ok thanks @mjhenkes !

**Comment by gerard-isdell** [comment] 2021-04-13 16:14
Are you able to give an estimate when this would be completed, or when the spike is due to be completed?

**Comment by sdadn** [comment] 2021-04-13 16:25
@gerard-isdell I am currently aiming to complete the spike within the next 2 weeks. But unfortunately, I won't have a detailed timeframe before that.

**Comment by gerard-isdell** [comment] 2021-04-20 15:57
Hi @sdadn Thanks for your help with this.  
In the end we used he resizeHandler to fix the issue
You can close this

**Closed** 2021-04-20 16:12 UTC
Labels: not a bug
